### ISSUE TITLE
Numbering  sections error

### ISSUE THREAD

**Issue by cortbreuer** [eddelbuettel/tint#39]
When I try using `number_sections: true` in my header to add section numbering and knit I get an error from yaml. Is this because numbered sections aren't allowed in tint, and if so is it possible to override that?

**Comment by eddelbuettel** [comment]
This _may_ be a Tufte special that numbers are outlawed.  I usually do without them here.  There may be a way to override which at current I cannot remember and cannot go searching for you.

Assume it is outlawed, unless you convince yourself otherwise.  As always, this _can_ be overrule if you want to fudge with the template.

Maybe also check old issues here, it may have come up before.

**Comment by eddelbuettel** [comment]
Oh, and if the error is from YAML then you are course trying to run before you walk. You *have to* get the yaml past the preprocessor before any of what I wrote in the first comment matters (at the latex level).
